portabilis/i-educar

ieducar/intranet/include/pessoa/clsEnderecoExterno.inc.php

Não ocorrendo erro ao cadastrar uma cidade com o nome "Cidade D'Agua", por exemplo.

Escapado strings no cadastro de endereço externo.

---

ieducar/lib/CoreExt/DataMapper.php

* Agora a mensagem informa o nome do registo que não foi encontrado e o id.

Tornado mensagem de nenhum registro encontrado mais amigável.

---

ieducar/intranet/educar_turma_cad.php

Olá @lucassch !
No seu commit 34a3c67e0b328e5219e4afd8d67a7259e04c7e0e foi removido os elementos html dos botões de cadastro rápido como o de série do cadastro de turma.
Porem você não removeu o código Javascript que dependia destes elementos, o que ocasionou um erro impeditivo no referido cadastro, impossibilitando a seleção de escolas.
Este erro afeta todos os usuários do i-Educar que atualizaram suas instalações recentemente.
Este pull request corrige este erro, removendo o código javascript agora desnecessário.

Corrigido erro no cadastro de turmas.

---

ieducar/intranet/educar_disciplina_xml.php

Recentemente foi relatado na lista da comunidade, que ao tentar cadastrar uma turma era exibido 'Erro 500' após selecionar a série.
Isto ocorre pois a API de componentes curriculares não trata erros ao carregar os dados.
Pore é disparado uma excessão "Nenhuma disciplina para a série (X) e a escola (Y) informados" quando não existe componentes vinculados a série, o que interrompe a renderização do XML com um erro 500 no servidor.
Este commit altera a API de disciplinas para retornar uma mensagem de erro amigável para o usuário nos casos de erro ao buscar os dados.

Trata erros ao carregar disciplinas da série na API de disciplinas.

---

ieducar/intranet/image_check.php

Algumas ferramentas como o php jasper report precisam que o caminho da
foto possua a extensão para detectar o tipo de imagem.

Alterado upload de foto do aluno para adicionar a extensão da imagem.

---

README.md

Ao clonar repositórios usar protocolo https ao invés de ssh. Estou fazendo essa sugestão pois o ssh só funciona se tivermos a chave configurada no repositório. Para quem estiver de fora o ideal seria clonar usando protocolo https mesmo, certo? O que acham?

Pequeno ajuste no README.md - git clone com https

---

.github/ISSUE_TEMPLATE/bugs.md
.github/ISSUE_TEMPLATE/outros.md
CONTRIBUTING.md
README.md

Proposta de guia de contribuição levando em consideração as discussões da issue #201 bem como o PR #211 e seus comentários.
Também contém sugestão de conteúdo que atente à issue #218.
Mudanças no README apontando para o guia, dentre outros pequenos ajustes.

Guia de contribuição

---

README.md
docker-compose.yml
docker/ieducar_1604/Dockerfile

Para remover dependência de ter de instalar o composer para depois instalar as dependências do projeto, foi adicionado ao docker-compose.yml a imagem oficia do composer

Adicionado composer ao docker-composer.yml

---

README.md

Badge oferecido pelo scrutinizer... informativo e enriquece o documento, **não cosmético**, seguindo tendências de outros projetos FOSS
Link #271

Scrutinizer score

---

website/package-lock.json

Após o merge do PR #373 foi identificado que o pacote unshiftio/url-parse possui uma vulnerabilidade em sua versão `1.4.1`. 
O mesmo foi atualizado para a versão `1.4.3`.
Detalhes na documentação: https://github.com/unshiftio/url-parse/blob/master/SECURITY.md#history

Usa a versão 1.4.3 do pacote unshiftio/url-parse

---

README.md
ieducar/configuration/ieducar.ini.sample

Quando estava testando o PR #369 ao executar os passos descritos no README, faltou o comando para copiar o arquivo `phinx.php`. 
Aproveitei para reorganizar os comandos a serem executados para iniciar o desenvolvimento e remover alguns comentários desnecessários do arquivo `ieducar.ini.sample`.

Atualiza readme com passos necessários para iniciar o desenvolvimento

---

docker-compose.yml

Composer não está efetuando a instalação das dependências. A imagem do docker composer é PHP 7.2 e há pacotes que exigem PHP 7.0, gerando erro.
Adicionado parâmetro para forçar instalação mesmo que não atenda os requisitos. Solução paliativa.

Corrige instalação de dependências via composer

---

composer.json
composer.lock
ieducar/configuration/ieducar.ini.sample
ieducar/lib/Portabilis/Controller/ReportCoreController.php
ieducar/lib/Portabilis/Report/ReportCore.php
ieducar/lib/Portabilis/Report/ReportFactory.php
ieducar/lib/Portabilis/Report/ReportFactoryPHPJasper.php
ieducar/lib/Portabilis/Report/ReportFactoryPHPJasperXML.php
ieducar/lib/Portabilis/Report/ReportFactoryRemote.php
ieducar/modules/Api/Views/ReportController.php
src/Reports/JsonDataSource.php

Com o crescimento da comunidade [i-Educar](https://ieducar.org/), adesões de novos municípios utilizando a versão community e o comprometimento da [Portabilis](https://www.portabilis.com.br/) com a comunidade, este patch visa preparar o [i-Educar](https://ieducar.org/) para receber o pacote de relatórios desenvolvidos pela [Portabilis](https://www.portabilis.com.br/) que serão liberados para a comunidade de maneira open source.
Atualmente, o pacote de relatórios apresentam alguns erros na emissão. Desta forma, estes relatórios serão removidos em prol do novo e mais atualizado pacote que irá conter mais de 40 relatórios.
Estes relatórios continuarão existindo neste novo pacote, porém foram atualizados a fim de utilizar uma arquitetura e tecnologia que melhor se adequa aos novos padrões …

Patch de ajustes para uso de relatórios

---

README.md
docker-compose.yml

Seguindo os passos do readme, sempre que o comando para rodar as migrations é executado, o Composer ainda não terminou de instalar as dependências e quem está rodando os comandos não consegue identificar o status atual da instalação devido o log não ser exibido.
Este pull request remove o serviço `composer` do `docker-compose.yml` e adiciona ao readme o comando para ser executado manualmente na sequencia correta.

Melhor instalação de dependências

---

.travis.yml

Com variáveis de ambiente, não é mais necessária a utilização do PostgreSQL client.
Remover ferramenta não utilizada do CI.

Remove PostgreSQL client do Travis

---

readme.md

Corrige os links para "Guia de contribuição" e "Código de conduta" no README.md que faziam referência a `CONTRIBUTING.md` e `CODE_OF_CONDUCT.md` e agora estão com outro nome `contributing.md` e `code-of-conduct.md`
Alterei os links que referenciavam esses arquivos antigos, colocando seus nomes atuais.
Corrige o erro 404 que era disparado por não encontrar o arquivo.
- ✅ Criei testes automatizados que cobrem minhas alterações.

Atualiza README.me, corrigindo contribuição e código de conduta

---

.gitignore
app/Console/Commands/LegacyLinkCommand.php
app/Http/Controllers/LegacyModuleRewriteController.php
ieducar/configuration/ieducar.ini.example
ieducar/includes/bootstrap.php
public/intranet/.gitignore
routes/web.php
server.php

Possibilita o uso do servidor interno do Laravel permitindo rodar o i-Educar apenas com o Postgres `9.5` e PHP `>=7.1.3` instalados localmente.
Não será mais necessário utilizar Docker para fazer demonstração ou iniciar o desenvolvimento, porém é aconselhável para garantir maior confiabilidade com a realidade de um serviço na web.
Para executar o i-Educar utilizando o servidor interno, execute o comando `php artisan serve`.
- Altera o comando que cria os links simbólicos para a aplicação legada.
- Adiciona um novo controller para simular as _rewrite rules_ de um servidor web.
- Cria novas rotas.
- Modifica as regras do servidor interno do Laravel.
Diminuir a barreira de entrada para novos desenvolvedores ou quem queira fazer demonstrações simples do i-Educar.
- ✅ New feature (Não quebra …

Rodar o i-Educar utilizando o servidor interno do Laravel

---

app/Http/Controllers/LegacyFakeAuthController.php

Após PR #482 foi identificado que erros poderiam ser gerados quando o Laravel Dusk é utilizado nos testes de browser e simula o login em uma request.

Corrige erro ao iniciar sessão no fake controller

---

app/Http/Middleware/ConnectTenantDatabase.php

Permite customizar a função que irá determinar qual conexão ao banco de dados deve ser a default. Serve para aplicação multi-tenanty definirem o banco de dados do cliente em tempo de requisição. 
Para utilizar uma função customizada, basta registrar no método `boot` do `AppServiceProvider`:
```php
use App\Http\Middleware\ConnectTenantDatabase;
use Illuminate\Http\Request;
public function boot()
{
ConnectTenantDatabase::setTenantResolver(function (Request $request) {
return $request->getHost();
});
}
```
A função deve retornar uma string que será utilizada como o nome da conexão.
- ✅ New feature (Não quebra outras funcionalidades e adiciona funcionalidades)
- ✅ Breaking change (Correção ou mudança, pode quebrar parte da aplicação)
- ✅ …

Melhora o middleware que define a conexão com o banco de dados

---

app/Http/Controllers/LegacyController.php

Qualquer rota que passa pelo `LegacyController` tem seus erros desativados devido ao código legado gerar notices e warnings.
Este PR irá permitir que ao definir `true` para `LEGACY_DISPLAY_ERRORS`, os erros sejam exibidos.
Isso irá ajudar na refatoração e melhoria da qualidade do código.

Permite desativar a supressão de erros

---

docker-compose.yml
docker/nginx/Dockerfile
docker/nginx/default.conf
docker/nginx/upstream.conf
docker/php/Dockerfile
ieducar/configuration/ieducar.ini.example

Desacopla a configuração do Nginx para escolher o upstream do PHP.
A instalação do i-Educar em servidor por muitas vezes ainda é dificultosa para quem não tem muita familiaridade com a configuração de servidores web.
A intenção deste PR é facilitar a instalação permitindo que o serviço PHP executado possa ser configurado a parte. Dessa forma basta copiar os arquivos `default.conf` e `upstream.conf`  para a pasta do Nginx. Apenas o arquivo `upstream.conf`, com 3 linhas apenas, que precisa ser alterado.
A instalação em um servidor é resumida aos comandos:
```
git clone https://github.com/portabilis/i-educar.git /var/www/ieducar
cd /var/www/ieducar
cp docker/nginx/default.conf /etc/nginx/conf.d/default.conf
cp docker/nginx/upstream.conf /etc/nginx/conf.d/upstream.conf
composer new-install …
```

Nginx upstream

---

tests/Unit/Services/CacheManagerTest.php
tests/Unit/Services/MenuServiceTest.php

Os testes de serviços estavam na pasta errada. Move para a pasta correta e limpa as classes.

Move testes para a pasta correta

---

ieducar/includes/bootstrap.php
ieducar/intranet/clsConfigItajai.inc.php
ieducar/intranet/download.php
ieducar/intranet/educar_instituicao_cad.php
ieducar/intranet/include/Geral.inc.php
ieducar/intranet/include/clsBanco.inc.php
ieducar/intranet/include/clsBase.inc.php
ieducar/intranet/include/clsControlador.inc.php
ieducar/intranet/include/pmicontrolesis/geral.inc.php
ieducar/intranet/include/pmieducar/geral.inc.php
ieducar/intranet/include/portal/geral.inc.php
ieducar/intranet/include/public/geral.inc.php
ieducar/intranet/include/urbano/geral.inc.php
ieducar/intranet/s3_config.php
ieducar/intranet/suspenso.php
ieducar/intranet/xml_acervo_geral.php
ieducar/modules/Educacenso/Views/IesAjaxController.php
ieducar/modules/TabelaArredondamento/Views/TabelaTipoNotaAjax.php

Remove requires do arquivo `bootstrap.php` para sua futura exclusão.
Modifica o comportamento para quando um ambiente não existir, lança uma exceção `NotFoundHttpException` ao invés de definir a propriedade `ambiente_inexistente`.
Implementação parcial da issue #532.

[2.2] Remove requires do arquivo `bootstrap.php`

---

ieducar/intranet/include/clsBase.inc.php
ieducar/lib/Portabilis/Controller/ReportCoreController.php
ieducar/lib/Portabilis/Mailer.php
ieducar/lib/Portabilis/Report/ReportFactoryPHPJasper.php
ieducar/lib/Portabilis/Utils/ReCaptcha.php
ieducar/modules/Api/Views/DiarioController.php
ieducar/modules/Avaliacao/Views/DiarioApiController.php
ieducar/vendor/autoload.php

Remove autoload.php fake que foi depreciado na versão 2.1.

[2.2] Remove autoload.php fake

---

.travis.yml

Adiciona ambiente com PHP 7.3 ao Travis e corrige a matriz de ambientes.
Antes os testes eram executados apenas na versão 7.1 do PHP, agora são executados na versão 7.1, 7.2 e 7.3.

[2.2] Adiciona ambiente com PHP 7.3 ao Travis

---

app/Setting.php
database/factories/SettingFactory.php
database/migrations/2019_01_01_100000_create_settings_table.php
tests/Unit/Eloquent/SettingTest.php

Cria tabela que armazenará as configurações que anteriormente estavam no arquivo `.ini`.
- A chave (_key_) deve ser alfanumérica minúscula separados os níveis por ponto final `app.entity.name`.
- O campo valor (_value_) será sempre um string, mas será convertido para seu determinado tipo no código PHP.
- Tipo (_type_) determina o tipo de campo e o cast que será feito no valor quando utilizado no código PHP. Pode ser `string`, `integer`, `float` ou `boolean`.
Implementação #527.

[2.2] Tabela para armazenar as configurações

---

ieducar/intranet/agenda.php
ieducar/intranet/scripts/agenda.js

Correção na exclusão de um compromisso
Correção do erro constatado pelo @edersoares na pull [550](https://github.com/portabilis/i-educar/pull/550), ao tentar excluir um compromisso dava erro:
`Uncaught TypeError: Cannot read property 'reset' of undefined
at excluir (agenda.php?cod_agenda=1&time=1553711156:680)
at <anonymous>:1:2`
- x Minhas alterações necessitam de alteração na documentação e já foram feitas.
- x Criei testes automatizados que cobrem minhas alterações.

Correção do erro na exclusão de um compromisso

---

.travis.yml

Após a atualização do ChromeDriver, existe problemas com os binários do Laravel Dusk que não estão conseguindo utilizar sessão ao executar os testes de browser. A intenção é habilitar novamente os testes de browser assim que o problema for corrigido.
Mais informações na issue https://github.com/laravel/dusk/issues/641.

Desabilita Dusk temporariamente

---

ieducar/intranet/include/pmieducar/clsPmieducarEscolaSerieDisciplina.inc.php

Não era considerado o valor NULL na lógica de cadastro/edição das séries da escola. A correção foi feita.
Fix #289.

Corrige lógica de edição das séries da escola

---

.travis.yml
composer.json
composer.lock

O PR https://github.com/portabilis/i-educar/pull/561 desabilitou a execução dos testes de browser no CI devido a problemas de incompatibilidade da versão do Chrome Driver. 
Este PR faz a correção e habilita novamente o Laravel Dusk no Travis.

Habilita o Laravel Dusk novamente

---

ieducar/lib/Portabilis/Report/ReportFactoryPHPJasper.php

A factory estava tentando mostrar o relatório o que causava conflito com o tratamento de output feito pelo `ReportCoreController`. A factory foi ajustada para apenas retornar o conteúdo do PDF quando este for gerado com sucesso.
Referente à issue #575 

Retorna conteúdo do PDF na factory PHP Jasper

---

database/migrations/legacy/2019_01_01_200000_add_foreign_keys_on_pmieducar_escola_table.php

A coluna `pmieducar.escola.codigo_lingua_indigena` é um array de inteiros e o Laravel não está apto a criar uma chave estrangeira para um array.
Por hora será removido a fim de permitir a atualização da versão 2.1 para 2.2, porém o problema deverá ser contornado de outra forma.

[2.2] Remove a chave estrangeira do código lingua indígena

---

docker/nginx/Dockerfile
docker/php/Dockerfile

Atualiza a versão do PHP para 7.3 utilizando o guia oficial https://www.php.net/migration73.

[2.2] Atualiza versão do PHP para 7.3

---

.travis.yml

Permite que o Travis faça uma instalação completa, incluíndo relatórios, do i-Educar para simular uma instalação utilizando Docker para desenvolvimento.

[2.2] Atualiza o CI para fazer teste do uso de Docker

---

.travis.yml

Instala a versão 74 do Chrome driver que permite executar os testes com Laravel Dusk sem erros.

[2.1] Utiliza a versão 74 do Chrome driver

---

public/js/install.js

Corrige problema discutido no fórum https://forum.ieducar.org/t/duvidas-ao-instalar-o-i-educar-no-ubuntu-18-04/594/9.
É necessário rodar todas as migrations antes de definir a senha do administrador.

[2.1] Inverte a ordem dos comandos de instalação

---

.travis.yml
docker/httpd/Dockerfile
docker/httpd/default.conf
docker/nginx/Dockerfile

Implementa suporte ao Apache HTTP Server como servidor web principal para rodar o i-Educar.
Ele pode ser utilizado em conjunto com o Nginx, mas por hora, será implementado de forma a se utilizar um ou outro.
Para quem quiser o utilizar o Apache via Docker, basta adicionar ao ser arquivo `docker-compose.override.yml` o seguinte trecho
```yml
httpd:
container_name: ieducar-httpd
build: docker/httpd
links:
- php
ports:
- 80
working_dir: /var/www/ieducar
volumes:
- ./:/var/www/ieducar
- ./docker/httpd/default.conf:/usr/local/apache2/conf/default.conf
```
Mapeie a porta, ou execute `docker-compose port httpd 80` para saber qual porta o Apache está respondendo.
Para quem quiser utilizar diretamente no servidor precisa definir um arquivo de configuração similar a este: …

[2.1] Suporte ao Apache HTTP Server

---

database/migrations/2019_01_01_200000_add_foreign_keys_in_employee_graduations_table.php
database/migrations/2019_01_01_200000_add_foreign_keys_in_school_managers_table.php
database/migrations/legacy/2019_01_01_200000_add_foreign_keys_on_pmieducar_menu_tipo_usuario_table.php

Ao executar `php artisan migrate:rollback` erros ao excluir chave estrangeira era apresentados, faz a correção.

[2.2] Corrige rollback das migrations

---

ieducar/modules/Api/Views/EnderecoController.php

Correção da query de buscar endereço pois esta buscando distrito errado
Quando digita um cep e o município tem mais de um distrito está buscando o distrito errado.
- x Minhas alterações necessitam de alteração na documentação e já foram feitas.
- x Criei testes automatizados que cobrem minhas alterações.

Correção da query de buscar endereço pois esta buscando distrito errado

---

docker/php/Dockerfile

**DESCRIÇÃO:**
Não faz sentido verificar se a hash do arquivo do composer baixado é igual a uma hash fixa dentro do workflow devido a atualizações no composer quebrarem essa etapa da do processo.
**AMBIENTE:**
- Plataforma utilizada (Docker, instalação direta)

[2.2] Remove hash de verificação do Composer no Dockerfile

---

docker/php/Dockerfile

Algumas pessoas apresentaram problemas na instalação do Java durante o processo de build do container, com isso para resolver o erro podemos alterar o **openjdk-8-jre** por **default-jdk** que a instalação do java irá ocorrer de forma continua sem problema algum e com isso a versão do Java instalada será a 11.

[2.2] Atualiza OpenJDK no Dockerfile

---

public/install.php
public/js/install.js

Permite utilizar o instalador para fazer o upgrade da versão [2.1](https://github.com/portabilis/i-educar/tree/2.1) para a versão [2.2](https://github.com/portabilis/i-educar/tree/2.2).
- É necessário executar o comando `link` sempre que a atualização é feita.
- Foi adicionado a versão ao JavaScript e CSS carregados para que o cache do navegador não atrapalhe.
É necessário utilizar  a release [2.1.25](https://github.com/portabilis/i-educar/releases/tag/2.1.25-upgrade) para fazer o upgrade através do instalador.
Refs #658.

[2.2] Permite utilizar o instalador para fazer o upgrade de versão

---

scripts/build

Ao realizar o build já troca o host da conexão com o banco de dados para `localhost`, assim é um passo que não será necessário fazer ao instalar a aplicação via instalador.

[2.2] Altera o host do banco de dados ao fazer build

---

docker/php/Dockerfile

O Laravel Dusk teve uma dependência adicionada e foi necessário adicionar a extensão `pcntl` a imagem PHP do Docker.

[2.2] Adiciona extensão pcntl a imagem PHP

---

docker/php/Dockerfile

O OpenJDK 11 era instalado em novos build da imagem PHP, porém o JasperStarter não tem funcionando nesta versão.
Altera para instalar a versão 8 do OpenJDK.

[2.2] Utiliza versão correta do Java

---

database/migrations/2019_10_02_095426_adiciona_coluna_historico_do_tipo_json_na_tabela_candidato_reserva_de_vagas.php

A coluna `historico` é necessária na tabela `pmieducar.candidato_reserva_vaga` e estava ocasionando o erro ao fazer uma nova matrícula.
Origem: https://forum.ieducar.org/t/erro-ao-matricular-aluno/846.

[2.2] Adiciona coluna esquecida

---

database/migrations/2020_02_16_100000_add_primary_column_in_configuracoes_gerais_table.php

Adiciona o schema da tabela na migration.
A falta disso está gerando o erro reportado no fórum
https://forum.ieducar.org/t/erro-na-instalacao-i-educar-2-2-20/950

Adiciona schema da tabela na migration

---

app/Services/UrlPresigner.php

Olá e obrigado por nos ajudar a tornar o i-Educar um projeto mais estável. Para abrir um pull request use o template abaixo:
**DESCRIÇÃO:**
O arquivo alterado na release 2.3.1 ainda precisou de ajustes, uma vez que o .env não mais contém a variável FILESYSTEM_CLOUD, que foi substituída por FILESYSTEM_DRIVER e como  padrão **default.cloud** devolve **s3** e não **local** como esperado, causando exceção na função.
A alteração ajuda na padronização do sistema pois a variável FILESYSTEM_DRIVER pode receber **local**, **minio** ou **s3** conforme o sistema de armazenamento utilizado pelo usuário.
**AMBIENTE:**
Descreva o ambiente em que este pull request foi criado.
- Plataforma utilizada (Docker, instalação direta)
- Sistema operacional e versão (Ubuntu 20.04)
- Navegador e versão (Chrome 83 …

Altera o UrlPresigner para permitir uso local usando filesystems.default

---

public/install.php

Após atualizar a versão para o Laravel 7, a biblioteca [Dotenv](https://github.com/vlucas/phpdotenv) teve seus construtor modificado sendo necessário fazer a alteração da invocação do método que carrega o arquivo `.env`.

[2.5] Corrige instalador

---

database/migrations/2021_01_22_000000_migrate_coutry_id_in_states_table.php

Migra ID do Brasil nos estados brasileiros.
Complemento do PR https://github.com/portabilis/i-educar/pull/743.

[2.5] Migra ID do Brasil nos estados brasileiros
