- ieducar/intranet/s3_config.php
* Corrigido e otimizado uso da variável global de configuração.
* Validado se configuração foi definida.
> Corrigido configuração AWS S3 usada para upload de fotos.

- ieducar/modules/Reports/ReportSources/portabilis_ficha_aluno.jrxml
Atualmente o relatório não exibe a foto do aluno.
> Corrigido relatório ficha do aluno para exibir a foto do aluno.

- ieducar/misc/database/migrations/20180612183130_adiciona_dependencias_schema_relatorio.php
Algumas funções do banco não estavam presentes no script que faz o setup inicial do banco
> Adiciona dependencias do esquema relatório que não estava presente no setup inicial do banco

- README.md
Necessário para saber como e onde se comunicar sobre determinados assuntos.
> Adicionando informações de comunicação no README

- README.md
> Corrigir link do Telegram

- ieducar/intranet/educar_importacao_educacenso.php
- ieducar/intranet/include/pmieducar/clsPmieducarEscola.inc.php
- ieducar/misc/database/migrations/20180629174827_remove_campo_banda_larga_escola.php
- ieducar/modules/Api/Views/EducacensoExportController.php
> Corrige problema no campo 87 (Banda larga) do registro 10 do Educacenso

- .gitignore
- .php_cs
- .scrutinizer.yml
- composer.json
- composer.lock
Link #211 , #233 , #260 
Resolve #234
> Code-sniffer

- README.md
Como discutido no #232, o docker é uma solução para demonstração ou desenvolvimento. Estou sugerindo um atenção para ninguém usar essa forma de instalação em produção. Quando tivermos uma manual faremos referencia a sessão que irá falar em varias formas de fazer deploy do i-Educar.
> Incluir atenção que Docker não é indicado para produção

- README.md
- docs/faq.md
Pessoal, como discutido anteriormente deixei uma primeira versão do FAQ feita!
Resolves #266
> Versão inicial de FAQ

- website/core/BlogGridBlock.js
- website/core/Footer.js
- website/npm-debug.log
- website/pages/en/index.js
- website/siteConfig.js
- website/static/css/custom.css
- website/static/en/js/conversao.js
- website/static/en/js/mailchimp.js
- website/static/en/js/map.js
- website/static/js/conversao.js
- website/static/js/map.js
Referência ao issue #297 - @MarceloCajueiro @fernandosjp 
* Uma landing page com as funcionalidades listadas.
* O Hero apenas com o nome do projeto e uma frase.
* Os últimos 3 posts do blog.
* Uma sessão com os parceiros.
* Página de documentação com texto genérico por enquanto.
* Mapa com as instâncias do i-Educar.
* Números sobre o projeto. (Agora é possível por meio do siteConfig.js colocar valores para os números do i-Educar no objeto `statistics`).
* Organização do código separando os componentes de maneira modular.
* Revisar textos, foram utilizados os textos previstos nos layouts entregues à minha equipe.
* Bloco com conversão e link para o github.
> Arrumando os erros do domínio e path das imagens.

- website/blog/2017-12-28-em-2018-queremos-o-i-educar-por-todo-o-brasil.md
- website/blog/2018-01-31-i-educar-por-todo-o-brasil-portabilis-e-fundacao-lemann.md
Hot fix do site. Posts de blog estão com conteúdo completo aparecendo na home.
Resolves #328
> Adicionar truncate aos posts do blog

- ieducar/modules/TransporteEscolar/Views/EmpresaController.php
- ieducar/modules/TransporteEscolar/Views/ItinerarioController.php
- ieducar/modules/TransporteEscolar/Views/MotoristaController.php
- ieducar/modules/TransporteEscolar/Views/PessoatransporteController.php
- ieducar/modules/TransporteEscolar/Views/PontoController.php
- ieducar/modules/TransporteEscolar/Views/RotaController.php
- ieducar/modules/TransporteEscolar/Views/VeiculoController.php
> Aplica PSR-2 em modules/TransporteEscolar

- composer.lock
> Atualiza composer.lock para refletir versões corretas

- README.md
Correção do link para a área de **comunicação**
> Atualização de link no README

- .scrutinizer.yml
- ieducar/configuration/ieducar.ini.sample
- phinx.php.sample
- phinx.php.scrutinizer
- Cria arquivo de conf do phinx pra ser usado no build do scrutinizer
- Altera valores dos arquivos de exemplo de configuração
> Altera arquivos de configuração do i-Educar e phinx pra simplificar a instalação

- ieducar/includes/bootstrap.php
- ieducar/intranet/include/clsCampos.inc.php
- ieducar/intranet/include/public/clsPublicBairro.inc.php
- ieducar/intranet/include/public/clsPublicUf.inc.php
Faz pequenas melhorias que evitam quebrar a aplicação.
> Melhorias de desenvolvimento

- ieducar/modules/Error/Mailers/NotificationMailer.php
- ieducar/modules/Error/Views/UnauthorizedController.php
- ieducar/modules/Error/Views/UnexpectedController.php
- ieducar/modules/HistoricoEscolar/Views/ProcessamentoApiController.php
- ieducar/modules/HistoricoEscolar/Views/ProcessamentoController.php
- ieducar/modules/OrdenacaoAlunos/Views/OrdenacaoAlunosApiController.php
- ieducar/modules/Portabilis/Assets/Version.php
Aplica PSR-2 em:
- modules/Portabilis
- modules/OrdenacaoAlunos
- modules/HistoricoEscolar
- modules/ExportaUsuarios
- modules/Error
> Aplica PSR-2 e remove comentários antigos de alguns arquivos

- .travis.yml
Adiciona o arquivo .travis.yml com as configurações para publicação da documentação pelo Docusaurus.
Closes #329.
> Adiciona o arquivo .travis.yml

- .travis.yml
- website/siteConfig.js
Apenas um teste para validar a publicação automática da documentação. Este PR pode ser revertido.
> Ajusta configurações do Travis para deploy da documentação somente após merge

- ieducar/intranet/include/clsControlador.inc.php
> Removido função que causava warning

- .scrutinizer.yml
Melhorias nas configurações do Scrutinizer
> Exclude jquery no Scrutinizer

- website/blog/2018-07-18-7-coisas-que-voce-precisa-saber-sobre-o-i-educar-no-fisl18.md
Adicionado novo post no blog relatando como foi a experiência da participação da Comunidade i-Educar no FISL 18 deste ano. 
A participação foi financiada pela Portabilis, mantenedora da solução e a Fundação Lemann, que está apoiando o projeto este ano.
> Novo post no blog: 7 coisas que você precisa saber sobre o i-Educar no FISL 18

- website/blog/2018-07-18-7-coisas-que-voce-precisa-saber-sobre-o-i-educar-no-fisl18.md
- website/package.json
Alterei o posicionamento da foto e do texto, para realizar o *truncate* do conteúdo e minimizar o tamanho da postagem na página inicial.
> Adicionando truncate para quebrar postagem de blog

- ieducar/intranet/include/urbano/clsUrbanoCepLogradouroBairro.inc.php
No meio do caminho tinha um **var_dump**
Tinha um **var_dump** no meio do caminho
Tinha um **die**
No meio do caminho tinha um **die**
> Remoção de var_dump e die

- website/blog/lancamento-de-pacote-de-relatorios-para-comunidade.md
Cria postagem para o blog do i-Educar sobre o lançamento do pacote de relatórios para a Comunidade
> Cria post sobre liberação de relatórios

- README.md
- ieducar/configuration/ieducar.ini.sample
Corrige comandos a serem executados para a instalação do pacote de relatórios do i-Educar.
> Atualiza readme para uso de relatórios

- ieducar/modules/Docente/Model/Licenciatura.php
- ieducar/modules/Docente/Model/LicenciaturaDataMapper.php
- ieducar/modules/Docente/Views/EditController.php
- ieducar/modules/Docente/Views/IndexController.php
- ieducar/modules/Docente/Views/ViewController.php
> PSR-2 em modules/Docente

- ieducar/lib/Utils/FileStream.class.php
- ieducar/lib/Utils/Mimetype.class.php
- ieducar/lib/Utils/SafeJson.php
- ieducar/modules/Docente/Model/Licenciatura.php
- ieducar/modules/Docente/Model/LicenciaturaDataMapper.php
- ieducar/modules/Docente/Views/EditController.php
- ieducar/modules/Docente/Views/IndexController.php
- ieducar/modules/Docente/Views/ViewController.php
Removi os comentários, refatorei um método e apliquei a PSR-2.
> PSR-2 em lib/Utils

- .gitignore
Separado arquivos que são de IDEs
Adicionado arquivos do Eclipse na lista
> Ignorando arquivos de IDEs

- ieducar/tests/Unit/Modules/Service/FaltaAlunoTest.php
> removendo skip desnecessário

- ieducar/misc/database/migrations/20181112171506_adiciona_nome_social_para_pessoa_fisica.php
- ieducar/misc/database/migrations/20181112173112_adiciona_nome_social_na_view_de_pessoa_fisica.php
É necessário executar esta migration antes de fazer o upgrade para a nova versão do i-Educar.
> Adiciona coluna do nome social

- composer.lock
Alinha a versão do composer.json e composer.lock.
> Alinha a versão do composer.json e composer.lock

- public/js/install.js
- src/Support/Installer.php
Na instalação em servidor, o comando que instala os relatórios não é rodado.
> Roda o comando de instalação dos relatórios

- composer.lock
> Atualiza dependências

- ieducar/intranet/include/clsBanco.inc.php
- tests/Unit/Core/ClsBancoTest.php
- tests/Unit/Core/ClsPmieducarQuadroHorarioHorariosTest.php
- tests/Unit/CoreExt/DataMapperTest.php
- tests/Unit/Modules/Service/TestCommon.php
Utiliza as credenciais da conexão do banco de dados ativa ao invés de buscar do arquivo `.ini`.
Irá ajudar na implementação da issue https://github.com/portabilis/i-educar/issues/527.
> Configurações do banco de dados

- app/Http/Middleware/LoadSettings.php
- tests/Unit/Http/Middleware/LoadSettingsTest.php
Carrega do banco de dados e sobrescreve as configurações em tempo de execução.
Implementação #527.
- ✅ New feature (Não quebra outras funcionalidades e adiciona funcionalidades)
- ✅ Criei testes automatizados que cobrem minhas alterações.
> [2.2] Middleware para carregar as configurações

- ieducar/intranet/agenda.php
- ieducar/intranet/scripts/agenda.js
- ieducar/intranet/styles/agenda.css
Correção do botão Novo compromisso não estava funcionando.
Quando clicava no botão Novo compromisso não estava abrindo a tela e correção no javascript pois o botão cancelar da tela não estava funcionando.
- Erro ao criar novo compromisso [#549](https://github.com/portabilis/i-educar/issues/549)
- x Minhas alterações necessitam de alteração na documentação e já foram feitas.
- x Criei testes automatizados que cobrem minhas alterações.
> Corrigindo erro no lançamento de novo compromisso

- ieducar/lib/App/Unificacao/Pessoa.php
Remoção das tabelas inexistentes declaradas no fluxo de unificação
Fixes #485
> Erro ao tentar unificar pessoas #485

- app/Http/Kernel.php
- app/Providers/AppServiceProvider.php
- ieducar/intranet/include/clsBase.inc.php
A branch [2.2](https://github.com/portabilis/i-educar/tree/2.2) tem gerado algumas divergências com a `master` na sua atualização, este patch irá aplicar espaços e modificações feitas na `2.2` para diminuir os conflitos na hora da atualização de código.
> Otimiza a diferenças de arquivos para versão 2.2

- app/Console/Commands/AdminPasswordCommand.php
- public/install.php
- src/Support/Installer.php
Com algumas mudanças na aplicação foi necessário atualizar também os scripts de instalação para refletir as modificações de ambiente e arquitetura.
> Correções nos scripts de instalação

- app/Console/Commands/DatabaseRestoreCommand.php
- app/Console/Commands/ImportSchoolGradeCommand.php
- app/Imports/SchoolGradeDisciplineImport.php
- app/Imports/SchoolGradeImport.php
- app/Models/LegacyEvaluationRule.php
- app/Services/StageScoreCalculationService.php
- composer.lock
- database/migrations/2019_07_12_100000_add_column_tipo_calculo_recuperacao_paralela.php
- database/migrations/2019_07_12_200000_migrate_column_media_recuperacao_paralela.php
- ieducar/intranet/educar_matricula_historico_cad.php
- ieducar/intranet/include/pessoa/clsCepLogradouro.inc.php
- ieducar/intranet/include/pmieducar/clsPmieducarMatriculaTurma.inc.php
- ieducar/modules/Api/Views/DiarioController.php
- ieducar/modules/Api/Views/RegraController.php
- ieducar/modules/Api/Views/ReportController.php
- ieducar/modules/Avaliacao/Service/Boletim.php
- ieducar/modules/Avaliacao/Views/DiarioApiController.php
- ieducar/modules/Configuracao/Views/ConfiguracaoMovimentoGeralController.php
- ieducar/modules/RegraAvaliacao/Assets/Javascripts/RegraAvaliacao.js
- ieducar/modules/RegraAvaliacao/Model/Regra.php
- ieducar/modules/RegraAvaliacao/Model/RegraDataMapper.php
- ieducar/modules/RegraAvaliacao/Model/TipoRecuperacaoParalela.php
- ieducar/modules/RegraAvaliacao/Views/EditController.php
- src/Modules/Educacenso/Data/Registro10.php
- src/Modules/EvaluationRules/Models/ParallelRemedialCalculationType.php
- tests/Unit/Services/StageScoreCalculationServiceTest.php
Antecipa atualizações da release.
> [2.2] Patch 25/07/2019

- app/Console/Commands/ImportDisciplineCommand.php
- composer.json
- composer.lock
- ieducar/intranet/include/pmieducar/clsPmieducarAluno.inc.php
- ieducar/modules/Api/Views/ReportController.php
> [2.2] Version 2.1.21

- readme.md
Atualiza o readme com links para o upgrade.
> [2.2] Atualiza o readme

- .travis.yml
- app/Console/Commands/ReportsInstallCommand.php
Comando para instalar os relatórios concedendo as devidas permissões, compilando os relatórios e rodando as migrations.
> [2.2] Comando de instalação dos relatórios

- .github/ISSUE_TEMPLATE/bugs.md
- .github/ISSUE_TEMPLATE/outros.md
> [2.2] Atualiza issue templates

- readme.md
> [2.2] Simplifica o readme

- app/Support/Database/WhenDeleted.php
- composer.lock
- database/migrations/2019_07_11_153049_create_pmieducar_aluno_excluidos_table.php
- database/migrations/2019_07_24_170452_alter_modules_componente_curricular_ano_escolar_excluidos_table.php
- ieducar/lib/App/Unificacao/Base.php
- ieducar/lib/App/Unificacao/Pessoa.php
- ieducar/modules/Api/Views/AlunoController.php
- tests/Unit/Support/Database/WhenDeletedTest.php
**Melhorias:**
- Sincroniza alunos deletados via banco ou via unificação de pessoas.
**Bugs:**
- Altera tabela e rotinas de componentes curriculares ano escolar excluídos.
Para mais detalhes, ver commits.
> [2.2] Portabilis patch 05/08/2019

- public/js/install.js
- src/Support/Installer.php
Estava sendo executados no instalador comandos já removidos.
> [2.2] Corrige comandos do instalador

- database/migrations/2019_09_01_100000_community_links.php
Migration para alterar links da comunidade.
Refs #650.
> [2.2] Migration para alterar links da comunidade

- app/Http/Controllers/Api/VersionController.php
- routes/api.php
Endpoint JSON para retornar a versão do i-Educar a fim de permitir a checagem da publicação no link https://comunidade.ieducar.com.br/.
> [2.2] Endpoint para retornar a versão do i-Educar

- readme.md
> [2.2] Ajusta badges para utilizar build do Travis

- tests/Feature/DiarioApi/DiarioApiFakeDataTestTrait.php
Corrige testes devido a ano fixo nos mockups de dados.
> [2.2] Corrige testes devido a ano fixo

- app/Repositories/EducacensoRepository.php
- app/Services/Educacenso/ImportService.php
- app/Services/Educacenso/Version2019/Registro10Import.php
- composer.json
- composer.lock
- database/migrations/2020_02_16_000000_keep_just_one_configuration.php
- database/migrations/2020_02_16_100000_add_primary_column_in_configuracoes_gerais_table.php
- ieducar/intranet/educar_turma_cad.php
- ieducar/intranet/include/portal/clsPortalFuncionario.inc.php
- ieducar/modules/Avaliacao/Service/Boletim.php
- ieducar/modules/Avaliacao/Views/PromocaoApiController.php
- tests/Feature/DiarioApi/DependencyTest.php
- tests/Feature/DiarioApi/DiarioApiFakeDataTestTrait.php
- tests/Feature/DiarioApi/DiarioApiRequestTestTrait.php
- tests/Feature/DiarioApi/ProgressionWithAverageCalculationWeightedRecoveryTest.php
- tests/Unit/Modules/Service/SituacaoTest.php
**Melhorias:**
- Adiciona namespace dos Reports no composer.json.
**Bugs:**
- Salva campo data de expiração corretamente.
- Trata campos opcionais na importação do registro 10.
- Utiliza ano letivo do formulário.
- Passa etapas no lançamento de faltas onde a etapa já foi concluída.
- Altera verificação de situação Aprovado com dependência.
**Refatoração:**
- Desabilita temporariamente o lançamento de faltas para casos em que a regra não usa nota.
- Remove usos da tabela endereco_externo.
- Migra e adiciona primária na tabela configuracoes_gerais.
- Code style.
Para mais detalhes, ver commits.
> Portabilis patch 22/02/2019

- config/legacy.php
Possibilita configurar o ReCAPTCHA v3 diretamente no arquivo .env
As novas chaves criadas são:
```
RECAPTCHA_V3_PUBLIC_KEY
RECAPTCHA_V3_PRIVATE_KEY
RECAPTCHA_V3_MINIMUM_SCORE
```
> Pega configurações do ReCAPTCHA no env

- ieducar/lib/Portabilis/Report/ReportFactoryPHPJasper.php
**Descrição**
Permite usar modifiers para fazer tratamento de dados nos relatórios.
> Permite modifiers na factory

- package.json
Atualiza dependências de segurança:
- Axios
- Laravel Mix
- Resolve URL Loader
> [2.5] Atualiza dependências

- .github/workflows/tests.yml
- readme.md
> [2.5] GitHub Actions badge

- composer.json
- composer.lock
> [2.4] Versão

- app/Providers/AppServiceProvider.php
- app/Providers/Postgres/DatabaseServiceProvider.php
- composer.lock
- public/js/install.js
- scripts/build
- src/Support/Installer.php
Após a migração arquitetural e o uso de pacotes plug and play foi necessário alterar o instalador do i-Educar em servidor.
> [2.6] Corrige o instalador em servidor

- package.json
- yarn.lock
Atualiza dependências do frontend.
> [2.6] Atualiza dependências
